import { StyleSheet, Platform, Dimensions } from "react-native"
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen"
import { _roundDimensions } from "./util"

import { SIZES, FONTS, COLORS } from "./theme"

export const GlobalStyles = StyleSheet.create({
  mainView: {
    // backgroundColor: COLORS.light_white,
    flex: 1,
  },
  contentView: {
    marginHorizontal: wp("4%"),
  },
  boxHeading: {
    flex: 0.5,
    // fontSize: wp('4%'),
    fontSize: wp("5.5%"),
    // fontFamily: FONTS.Font_Semibold,

    ...FONTS.h2,
    color: COLORS.black,
    textAlign: "left",
  },
  viewAll: {
    flex: 0.5,
    fontSize: wp("3.4%"),
    fontFamily: FONTS.Font_Semibold,
    textTransform: "uppercase",
    color: COLORS.link_color,
    textAlign: "right",
    padding: 8,
  },
  outstockview: {
    backgroundColor: COLORS.red,
    padding: wp("0.8%"),
    width: wp("18%"),
    position: "absolute",
    top: hp("1.2%"),
    justifyContent: "center",
    alignItems: "center",
    left: wp("2%"),
    overflow: "hidden",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.3 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    borderRadius: wp("1%"),
    elevation: 3,
  },
  outofstockTxt: {
    color: COLORS.white,
    fontFamily: FONTS.Catamaran_SemiBold,
    fontSize: wp("2.6%"),
    textAlign: "center",
  },
  newtextView: {
    backgroundColor: COLORS.white,
    padding: wp("0.8%"),
    width: wp("12%"),
    position: "absolute",
    top: hp("1.2%"),
    left: wp("2%"),
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.3 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    borderRadius: wp("1%"),
    elevation: 3,
  },
  newTxt: {
    color: COLORS.text_color,
    fontFamily: FONTS.Catamaran_SemiBold,
    fontSize: wp("2.8%"),
    textAlign: "center",
  },
  unFavCircle: {
    backgroundColor: COLORS.light_white,
    height: _roundDimensions()._height * 0.04,
    width: _roundDimensions()._height * 0.04,
    borderRadius: _roundDimensions()._borderRadius,
    overflow: "hidden",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  FavCircle: {
    backgroundColor: COLORS.light_white,
    height: _roundDimensions()._height * 0.04,
    width: _roundDimensions()._height * 0.04,
    borderRadius: _roundDimensions()._borderRadius,
    overflow: "hidden",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  unFavIcon: {
    fontWeight: "700",
    fontSize: wp("3.8%"),
  },
  headerLeft: {
    flex: 0.1,
    marginLeft: wp("5%"),
    justifyContent: "center",
    alignItems: "center",
  },
  headerCenter: {
    flex: 0.8,
    marginLeft: wp("5%"),
    justifyContent: "center",
    alignItems: "flex-start",
  },
  headingTxt: {
    fontFamily: FONTS.Font_Bold,
    fontSize: wp("3.5%"),
    color: COLORS.text_color,
  },
  headerRight: {
    flex: 0.1,
    justifyContent: "center",
    alignItems: "center",
    height: _roundDimensions()._height * 0.042,
    width: _roundDimensions()._height * 0.04,
    borderRadius: _roundDimensions()._borderRadius,
    backgroundColor: COLORS.white,
    marginRight: wp("4%"),
    padding: 4,
  },
  horizontalLine: {
    width: wp("90%"),
    alignSelf: "center",
    height: 0.5,
    backgroundColor: COLORS.light_white,
  },

  tabBarView: {
    backgroundColor: COLORS.light_white,
    alignItems: "center",
    justifyContent: "center",
    width: wp("100%"),
    height: Platform.OS === "ios" ? wp("22%") : wp("15%"),
    flexDirection: "row",
    marginTop: hp("1%"),
  },
  tabbarText: {
    alignSelf: "center",
    fontSize: Platform.isPad === true ? wp("3%") : wp("5%"),
    marginLeft: Platform.isPad === true ? wp("1%") : wp("2%"),
    fontFamily: FONTS.Font_Semibold,
    flex: 1,
    color: COLORS.text_color,
  },

  authtabbarText: {
    // alignSelf : "center",
    fontSize: Platform.isPad === true ? wp("3%") : wp("6%"),
    // marginLeft: wp('5%'),
    ...FONTS.Font_Reguler,
    // flex: 1,
    color: COLORS.text_color,
    lineHeight: hp("5%"),
  },

  authSubText: {
    fontSize: Platform.isPad === true ? wp("3%") : wp("3.5%"),
    fontFamily: FONTS.Font_Reguler,
    color: "#767787",
    marginLeft: wp("5%"),
  },

  mainProductView: {
    backgroundColor: COLORS.light_white,
    // flex: 0.5,
    height: Platform.isPad === true ? wp("50%") : wp("75%"),
    width: Platform.isPad === true ? wp("30%") : wp("46%"),
    // margin: wp('2%'),
    marginBottom: wp("3%"),
    marginRight: wp("3%"),
    borderRadius: wp("2%"),

    // mange Shadow
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.3 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
    // shadowOpacity: Platform.OS === 'ios' ? 0.20 : 10,
    // shadowRadius: 5,
    // shadowOffset: { height: 0, weight: 0 },
    // shadowColor: 'black',
    // elevation: 10,
  },
  mainCategoriesView: {
    backgroundColor: COLORS.light_white,
    // flex: Platform.isPad === true ? 1 : 0.5,
    height: Platform.isPad === true ? wp("45%") : wp("60%"),
    width: Platform.isPad === true ? wp("30%") : wp("46%"),
    // margin: wp('2%'),
    marginBottom: wp("3%"),
    marginRight: wp("3%"),
    borderRadius: wp("2%"),

    // mange Shadow
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.3 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
    // shadowOpacity: Platform.OS === 'ios' ? 0.10 : 10,
    // shadowRadius: 2,
    // shadowColor: 'black',
  },
  mainWishProductView: {
    // flex: 0.5,
    padding: Platform.isPad === true ? wp("1.5%") : wp("3%"),
    alignItems: "center",
    flexDirection: "row",
    borderBottomWidth: wp("0.1%"),
    borderColor: COLORS.dark_gray_text,
    borderRadius: wp("2%"),

    // mange Shadow
    // shadowOpacity: Platform.OS === 'ios' ? 0.20 : 10,
    // shadowRadius: 5,
    // shadowColor: 'black',
    // elevation: 10,
  },
  button: {
    height: Platform.isPad === true ? wp("8%") : wp("14%"),
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    // borderRadius: 14,
    // backgroundColor : COLORS.mainColor
    // shadowColor: 'rgba(0,0,0, .4)',
    // shadowOffset: {height: 1, width: 1},
    // shadowOpacity: 1,
    // shadowRadius: 1,
    // elevation: 2,
  },
  buttonText: {
    // ...FONTS.Font_Bold,
    color: COLORS.white,
    fontSize: Platform.isPad === true ? wp("3.5%") : wp("4.5%"),
  },

  formControlStyle: {
    borderRadius: 20,
  },
  textInputStyle: {
    height: wp("14%"),
    fontFamily: FONTS.Font_Reguler,
    fontSize: Platform.isPad === true ? wp("4.5%") : wp("4.2%"),
    color: COLORS.secondary_text_color,
    padding: 5,
    borderColor: COLORS.danger,
  },
  textInputStyleMain: {
    height: wp("14%"),
    fontFamily: FONTS.Font_Reguler,
    fontSize: Platform.isPad === true ? wp("4.5%") : wp("4.2%"),
    color: COLORS.secondary_text_color,
    padding: 5,
  },
  textAreaInputStyle: {
    height: wp("20%"),
    fontFamily: FONTS.Catamaran_Bold,
    backgroundColor: COLORS.white,
    fontSize: Platform.isPad === true ? wp("3.5%") : wp("3.2%"),
    color: COLORS.secondary_text_color,
    padding: 5,

    // borderColor: Colors.light_gray
  },
  textInputStyle2: {
    height: wp("15%"),
    // padding: 5,
    fontFamily: FONTS.Font_Reguler,
    // backgroundColor: COLORS.white,
    width: wp("44%"),
    color: COLORS.black,
  },
  shadowInput: {
    elevation: 4,
  },
  authHeader: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    marginTop: hp("1.5%"),
  },
  // Home screen global view ------------------------------------------------------------- >>>>>>>>>>
  mainViewHomeProduct: {
    backgroundColor: COLORS.light_white,
    width: Platform.isPad === true ? wp("30%") : wp("40%"),
    height: Platform.isPad === true ? wp("50%") : wp("70%"),
    margin: Platform.isPad === true ? wp("1.5%") : wp("2%"),
    borderRadius: wp("2%"),

    // mange Shadow
    shadowColor: "black",
    shadowOffset: { width: 0, height: 0.3 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 5,
    // shadowOpacity: Platform.OS === 'ios' ? 0.10 : 10,
    // shadowRadius: 2,
    // shadowColor: 'black',
  },
  gridViewHomeProduct: {
    backgroundColor: COLORS.white,
    flex: 0.5,
    height: wp("50%"),
    margin: wp("2%"),
    borderRadius: wp("2%"),
    // mange Shadow
    shadowOpacity: Platform.OS === "ios" ? 0.1 : 10,
    shadowRadius: 2,
    shadowColor: "black",
    elevation: 10,
  },
  gridMainView: {
    backgroundColor: COLORS.white,
    paddingVertical: wp("3%"),
    // mange Shadow
    shadowOpacity: Platform.OS === "ios" ? 0.1 : 10,
    shadowRadius: 2,
    shadowColor: "black",
    elevation: 10,
  },
  TopBrandView: {
    backgroundColor: COLORS.white,
    width: wp("40%"),
    height: wp("70%"),
    margin: wp("2%"),
    borderRadius: wp("2%"),
    // mange Shadow
    shadowOpacity: Platform.OS === "ios" ? 0.1 : 10,
    shadowRadius: 2,
    shadowColor: "black",
    elevation: 10,
  },
  mainViewHomeProductHeader: {
    // flex: 1,
    paddingHorizontal: wp("3%"),
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  mainTextHomeProductHeader: {
    fontSize: Platform.isPad === true ? wp("3%") : wp("4.5%"),
    fontFamily: FONTS.Font_Reguler,
    // flex: 1,
  },
  seeAllTextHomeProduct: {
    fontSize: Platform.isPad === true ? wp("2.5%") : wp("4%"),
    fontFamily: FONTS.Catamaran_Regular,
    // color: Colors.black
  },

  backIcon: {
    margin: wp("2%"),
    padding: wp("2%"),
    height: Platform.isPad === true ? wp("4%") : wp("6%"),
    width: Platform.isPad === true ? wp("4%") : wp("6%"),
    tintColor: COLORS.black,
    transform: [{ rotate: "180deg" }],
  },
  nextIcon: {
    margin: wp("2%"),
    padding: wp("2%"),
    height: wp("4%"),
    width: wp("4%"),
    transform: [{ rotate: "180deg" }],
  },
  loader: {
    marginVertical: Dimensions.get("screen").height / 3,
  },
  badge: {
    position: "absolute",
    top: -14,
    right: 3,
    height: 24,
    width: 24,
    borderRadius: 12,
    backgroundColor: COLORS.themeColor,
    justifyContent: "center",
  },
  badgeText: {
    color: COLORS.white,
    textAlign: "center",
    fontSize: wp("3%"),
    fontFamily: FONTS.Font_Semibold,
  },

  noRecord: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    marginTop: hp("25%"),
  },
  emptyTxt: {
    fontSize: wp("6%"),
    marginVertical: hp("1.5%"),
    fontFamily: FONTS.Font_Semibold,
    color: COLORS.secondary_text_color,
  },

  t7: {
    fontFamily: FONTS.Font_Reguler,
    fontSize : SIZES.h4,
    color: COLORS.black,
  },
})
